// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddPasswordItem(arg1) {
  return window['go']['main']['App']['AddPasswordItem'](arg1);
}

export function ChangeMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeMasterPassword'](arg1, arg2);
}

export function ClearClipboard() {
  return window['go']['main']['App']['ClearClipboard']();
}

export function CopyToClipboard(arg1, arg2) {
  return window['go']['main']['App']['CopyToClipboard'](arg1, arg2);
}

export function CreateVault(arg1) {
  return window['go']['main']['App']['CreateVault'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeletePasswordItem(arg1) {
  return window['go']['main']['App']['DeletePasswordItem'](arg1);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function ExportToExcel() {
  return window['go']['main']['App']['ExportToExcel']();
}

export function GeneratePassword(arg1) {
  return window['go']['main']['App']['GeneratePassword'](arg1);
}

export function GetAllCategories() {
  return window['go']['main']['App']['GetAllCategories']();
}

export function GetAllPasswordItems() {
  return window['go']['main']['App']['GetAllPasswordItems']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetPasswordItem(arg1) {
  return window['go']['main']['App']['GetPasswordItem'](arg1);
}

export function GetVaultState() {
  return window['go']['main']['App']['GetVaultState']();
}

export function ImportBackup(arg1) {
  return window['go']['main']['App']['ImportBackup'](arg1);
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function OnSuspend() {
  return window['go']['main']['App']['OnSuspend']();
}

export function ReorderCategories(arg1) {
  return window['go']['main']['App']['ReorderCategories'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function StartUpdate(arg1) {
  return window['go']['main']['App']['StartUpdate'](arg1);
}

export function SyncConfig(arg1) {
  return window['go']['main']['App']['SyncConfig'](arg1);
}

export function TrackUsage(arg1) {
  return window['go']['main']['App']['TrackUsage'](arg1);
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}

export function UpdateCategory(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdatePasswordItem(arg1, arg2) {
  return window['go']['main']['App']['UpdatePasswordItem'](arg1, arg2);
}

export function VaultExists() {
  return window['go']['main']['App']['VaultExists']();
}
