// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function AddCategory(arg1:string):Promise<models.Category>;

export function AddPasswordItem(arg1:models.NewPasswordItem):Promise<models.PasswordItem>;

export function ChangeMasterPassword(arg1:string,arg2:string):Promise<void>;

export function ClearClipboard():Promise<void>;

export function CopyToClipboard(arg1:string,arg2:number):Promise<void>;

export function CreateVault(arg1:string):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeletePasswordItem(arg1:string):Promise<void>;

export function ExportBackup():Promise<void>;

export function ExportToExcel():Promise<void>;

export function GeneratePassword(arg1:services.PasswordOptions):Promise<services.PasswordGenerationResult>;

export function GetAllCategories():Promise<Array<models.Category>>;

export function GetAllPasswordItems():Promise<Array<models.PasswordItem>>;

export function GetConfig():Promise<models.AppConfig>;

export function GetLanguage():Promise<string>;

export function GetPasswordItem(arg1:string):Promise<models.PasswordItem>;

export function GetVaultState():Promise<string>;

export function ImportBackup(arg1:string):Promise<void>;

export function LockVault():Promise<void>;

export function OnSuspend():Promise<void>;

export function ReorderCategories(arg1:Array<string>):Promise<void>;

export function ResetConfig():Promise<models.AppConfig>;

export function SetLanguage(arg1:string):Promise<void>;

export function SyncConfig(arg1:models.AppConfig):Promise<models.AppConfig>;

export function TrackUsage(arg1:string):Promise<void>;

export function UnlockVault(arg1:string):Promise<models.Vault>;

export function UpdateCategory(arg1:string,arg2:string):Promise<models.Category>;

export function UpdateConfig(arg1:models.AppConfig):Promise<models.AppConfig>;

export function UpdatePasswordItem(arg1:string,arg2:Record<string, any>):Promise<models.PasswordItem>;

export function VaultExists():Promise<boolean>;
